config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get '/signup', to: 'users#new'
  get '/users', to: 'users#show'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  get '/map', to: 'map#index'
  post '/shopreview', to: 'shopreview#create'
  delete '/shopreview/:id', to: 'shopreview#destroy'
  get '/shops/:id', to: 'shops#show'
  resources :users
  resources :shops

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_reviews, dependent: :destroy
  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/shop_review.rb
class ShopReview < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shop_reviews, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user, :logged_in?
  before_action :require_login

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def require_login
    return if logged_in?

    redirect_to root_path, notice: 'このページにアクセスするにはログインが必要です'
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate

  def index
    @shops = Shop.all
  end

  private

  def authenticate
    return if logged_in?

    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def create
    user = User.find_by(email: params[:session][:email].downcase)&.authenticate(params[:session][:password])
    if user
      log_in user
      redirect_to map_path, notice: 'ログインに成功しました'
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to login_path, notice: 'ログアウトしました'
  end
end

app/controllers/shopreview_controller.rb
class ShopreviewController < ApplicationController
  def create
    shop = Shop.find(params['shop_id'])
    @shop_review = ShopReview.new(user: current_user, shop: shop, comment: params['comment'])
    if @shop_review.save
      redirect_to shop_path(shop), notice: 'レビューを投稿しました'
    else
      redirect_to root_path
    end
  end

  def destroy
    @shop_review = current_user.shop_reviews.find(params[:id])

    if @shop_review.destroy
      redirect_to shop_path(@shop_review.shop_id), notice: 'レビューを削除しました'
    else
      redirect_to shop_path(@shop_review.shop_id), alert: 'レビュー削除に失敗しました'
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate

  def show
    @shop = Shop.find(params['id'])
    @shop_reviews = @shop.shop_reviews.order(created_at: :desc).page(params[:page])
  end

  private

  def authenticate
    return if logged_in?

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to map_path, notice: 'ユーザーを作成しました'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/shopreview_helper.rb
module ShopreviewHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/application/_flash.html.erb
<% if flash[:notice] %>
<div
  data-controller="notification"
  data-notification-delay-value="2000"
  class="transition transform duration-1000 hidden bg-blue-600 text-white font-bold"
  data-transition-enter-from="opacity-0 translate-x-6"
  data-transition-enter-to="opacity-100 translate-x-0"
  data-transition-leave-from="opacity-100 translate-x-0"
  data-transition-leave-to="opacity-0 translate-x-6"
>
  <p><%= flash[:notice] %></p>

  <button data-action="notification#hide">閉じる</button>
</div>
<% end %>

<% if flash[:alert] %>
<div
  data-controller="notification"
  data-notification-delay-value="2000"
  class="transition transform duration-1000 hidden bg-red-500 text-white font-bold"
  data-transition-enter-from="opacity-0 translate-x-6"
  data-transition-enter-to="opacity-100 translate-x-0"
  data-transition-leave-from="opacity-100 translate-x-0"
  data-transition-leave-to="opacity-0 translate-x-6"
>
  <p><%= flash[:alert] %></p>

  <button data-action="notification#hide">閉じる</button>
</div>
<% end %>

app/views/application/_header.html.erb
<header class="bg-blue-600 text-white opacity-90">
    <div class="container mx-auto px-4 grid grid-cols-2 items-center">
    <% if logged_in? %>
    <%= link_to "Mapapp", map_path, class: "text-3xl font-bold" %>
    <% else %>
    <h1 class="text-3xl font-bold">Mapapp</h1>
    <% end %>
    <nav class="md:flex justify-end space-x-4">
      <% if logged_in? %>
        <%= link_to "ログアウト", logout_path, data: {
              turbo_method: "delete",
              turbo_confirm: "ログアウトしますか？"
            } %>
      <% else %>
        <%= link_to "ログイン", login_path %>
        <%= link_to "新規登録", signup_path %>
      <% end %>
    </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mapapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "application/header" %>
    <%= render "application/flash" %>
    <%= yield %>
  </body>
</html>

app/views/map/_content_window.html.erb
<div class="flex flex-col items-center justify-center">
  <h2 class="font-bold text-center mb-2">
    <%= shop.name %>
  </h2>
  <%= image_tag("shop/#{shop.code}.jpg", class: "small-image") %>
  <%= link_to "お店の詳細へ", shop_path(shop), class: "bg-blue-600 text-white font-bold my-2 px-4 py-2 rounded" %>
</div>

app/views/map/index.html.erb
<div id='map'></div>

<script>
let map;
let infoWindows = [];

function closeAllInfoWindows() {
  for (let i = 0; i < infoWindows.length; i++) {
    infoWindows[i].close();
  }
}

function initMap() {
  geocoder = new google.maps.Geocoder();

  map = new google.maps.Map(document.getElementById('map'), {
    center: { lat: 35.68128415327956, lng: 139.76676039246024 },
    zoom: 15,
  });

  <% @shops.each do |shop| %>
    let markerData<%= shop.id %> = {
      id: <%= shop.id %>,
      position: {
        lat: <%= shop.latitude %>,
        lng: <%= shop.longitude %>
      },
      infoWindowContent: `<%= render partial: "content_window", locals: { shop: shop } %>`
    };
  
    let marker<%= shop.id %> = new google.maps.Marker({
      map: map,
      position: markerData<%= shop.id %>.position
    });
  
    let infoWindow<%= shop.id %> = new google.maps.InfoWindow({
      content: markerData<%= shop.id %>.infoWindowContent,
      maxWidth: 600
    });
  
    marker<%= shop.id %>.addListener('click', () => {
      infoWindow<%= shop.id %>.open(map, marker<%= shop.id %>);
    });
  <% end %>
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/shopreview/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Shopreview#create</h1>
  <p>Find me in app/views/shopreview/create.html.erb</p>
</div>

app/views/shops/show.html.erb
<div class="flex flex-col items-center">
  <h1 class="text-xl font-bold">
    <%= @shop.name %>
  </h1>
  <%= image_tag("shop/#{@shop.code}.jpg", class: "small-image") %>
</div>

<div class="py-4">
<h2 class="text-2xl font-bold">このお店のレビュー</h2>
<% if @shop.shop_reviews.any? %>
  <ul>
    <% @shop_reviews.each do |review| %>
      <li class="bg-white shadow-md rounded-md p-4 mb-4"> <div class="flex items-center">
          <%= gravatar_for(review.user) %>
          <div class="ml-4">
            <h3 class="text-lg font-bold"><%= review.user.name %></h3>
            <p class="text-sm text-gray-500">投稿時間: <%= l review.created_at, format: :long %></p>
            <hr class="my-2"><p class="text-gray-700"><%= review.comment %></p>
            <% if current_user == review.user %>
              <p class="text-red-500 mt-2"> <%= link_to "投稿したレビュー削除", "/shopreview/#{review.id}", data: { turbo_method: :delete, turbo_confirm: "レビューを削除しますか?" } %>
              </p>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @shop_reviews %>
<% else %>
  <p>まだレビューはありません。</p>
<% end %>
</div>

<div class="flex flex-col items-center">
  <%= form_with(model: @shopreview, url: shopreview_path, remote: true) do |form| %>
    <div class="mb-4">
      <%= form.hidden_field :shop_id, value: @shop.id %>
      <%= form.text_area :comment, class: "w-full p-2 border border-gray-300 rounded-md", rows: 6, placeholder: "レビューを入力してください" %>
    </div>
    <div class="text-center">
    <%= form.submit "レビューを送信", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form-container">
  <%= form_with model: @user, class: "w-full max-w-sm mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 opacity-90" do |f| %>
      <div class="mb-4">
        <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
        <%= f.text_field :name, class: "mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" %>
      </div>

      <div class="mb-4">
        <%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
        <%= f.email_field :email, class: "mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" %>
      </div>

      <div class="mb-4">
        <%= f.label :password, class: "block text-sm font-medium text-gray-700" %>
        <%= f.password_field :password, class: "mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" %>
      </div>

      <div class="mb-4">
        <%= f.label :password_confirmation, "Confirmation", class: "block text-sm font-medium text-gray-700" %>
        <%= f.password_field :password_confirmation, class: "mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" %>
      </div>

      <div class="flex items-center justify-center">
      <%= f.submit "Create my account", class: "inline-flex items-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>

  <video autoplay loop muted src="/videos/imagevideo.mp4" style="width: 100%; height: 100%; object-fit: cover;"></video>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>